ALTER TABLE "Settings"
ADD COLUMN IF NOT EXISTS "hideYouTubeShorts" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Item"
ADD COLUMN IF NOT EXISTS "youtubeIsShort" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Item"
ADD COLUMN IF NOT EXISTS "youtubeShortCheckedAt" TIMESTAMP(3);
